### ISSUE TITLE
Lets encrypt 

### ISSUE THREAD

**Issue by furby** [gjyoung1974/kolide-fleet-chart#1]
Hi,
I got my deployment of fleet up and running great on Kubernetes. A question though.
What would I need to change on the https://github.com/gjyoung1974/kolide-fleet-chart/blob/master/fleet/values.yaml
in order to use Letsencrypt?

**Comment by gjyoung1974** [comment]
I realize this is a year old now @furby 
Have you found the solution?

I would take a look at cert manager

https://docs.bitnami.com/tutorials/secure-kubernetes-services-with-ingress-tls-letsencrypt

**Comment by furby** [comment]
Hey, yes I did.
I ended up using an ingress instead of the load balancer. Here it is if it's useful for anyone else. 

```
apiVersion: {{.Values.ingressApiVersion}}
kind: Ingress
metadata:
  name: {{.Values.dnsHostName}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/grpc-services: "grpc-svc"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    certmanager.k8s.io/acme-dns01-provider: prod-clouddns
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: "{{.Values.dnsHostName}}"
    http:
      paths:
      - backend:
          serviceName: "{{.Values.fleetName}}"
          servicePort: {{ .Values.fleetSvcExtPort }}
  tls:
  - hosts:
    - "{{.Values.dnsHostName}}"
    secretName: "{{.Values.fleetName}}-https"
```

Thanks for the charts also, was great to have them
